version: '2'
services:
  gate:
    restart: always
    build: ./gate/
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  web:
    image: occano/cloud-server
    ports:
      - 8000:8000
